const slug = (s) => s.toLowerCase().normalize("NFD").replace(/\p{Mn}/gu,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");

const nicheSeeds = [
  { name: "Rouge Malachite", brand: "Armani Privé", gender: "Mixte", description: "Oriental boisé profond et précieux." },
  { name: "Verte Malachite", brand: "Armani Privé", gender: "Mixte", description: "Émeraude végétale rare et raffinée." },
  { name: "Cuir Beluga", brand: "Guerlain", gender: "Mixte", description: "Cuir velouté, vanille et héliotrope." },
  { name: "Montale Roses Musk", brand: "Montale", gender: "Femme", description: "Roses opulentes sur lit de musc blanc." },
  { name: "Red Oud", brand: "Montale", gender: "Mixte", description: "Oud rouge intense et résineux.", bestSeller: true },
  { name: "Black Oud", brand: "Montale", gender: "Mixte", description: "Oud noir mystérieux et boisé." },
  { name: "Fleur Narcotique", brand: "Nishane", gender: "Mixte", description: "Floral fruité hypnotique culte.", bestSeller: true },
  { name: "Fucking Fabulous", brand: "Tom Ford", gender: "Mixte", description: "Cuir, amande et lavande iconique." },
  { name: "Joop! Homme", brand: "Joop!", gender: "Homme", description: "Oriental fleuri rouge mythique." },
  { name: "Pegasus", brand: "Parfums de Marly", gender: "Homme", description: "Amande, héliotrope et vanille luxueux." },
  { name: "Noir de Noir", brand: "Tom Ford", gender: "Mixte", description: "Rose noire, truffe et patchouli." },
  { name: "Erba Pura", brand: "Xerjoff", gender: "Mixte", description: "Fruité méditerranéen ultra raffiné.", bestSeller: true },
  { name: "Tom Ford Noir Extreme", brand: "Tom Ford", gender: "Homme", description: "Oriental gourmand sophistiqué." },
  { name: "Le Parfum Mercedes-Benz", brand: "Mercedes-Benz", gender: "Homme", description: "Boisé chypré moderne et élégant." },
  { name: "Sunshine", brand: "Amouage", gender: "Femme", description: "Solaire, gourmand et radieux." },
  { name: "Alexandria II", brand: "Xerjoff", gender: "Mixte", description: "Oud miellé, ambré et vanille rare." },
  { name: "Métallique", brand: "Tom Ford", gender: "Mixte", description: "Lavande poudrée et fleur d'oranger." },
  { name: "Cartier La Panthère", brand: "Cartier", gender: "Femme", description: "Chypre floral félin et magnétique." },
  { name: "Mandarino di Amalfi", brand: "Tom Ford", gender: "Mixte", description: "Mandarine de Sicile lumineuse." },
  { name: "Yellow Diamond Intense", brand: "Versace", gender: "Femme", description: "Floral fruité scintillant." },
  { name: "Coco Vanille", brand: "Mancera", gender: "Mixte", description: "Coco crémeux, vanille et oud doux.", bestSeller: true },
  { name: "Dolce & Gabbana The One", brand: "Dolce & Gabbana", gender: "Femme", description: "Oriental floral chaleureux." },
  { name: "Costa Azzurra", brand: "Tom Ford", gender: "Mixte", description: "Évasion marine méditerranéenne." },
  { name: "Stronger With You Amber", brand: "Armani", gender: "Homme", description: "Ambre, miel et tabac magnétique." },
  { name: "Aïsha", brand: "Christian Dior", gender: "Femme", description: "Floral oriental précieux." },
  { name: "Attrape-Rêves", brand: "Louis Vuitton", gender: "Femme", description: "Pêche solaire, jasmin et caramel." },
  { name: "Ombré Leather", brand: "Tom Ford", gender: "Mixte", description: "Cuir suédé et fleur de patchouli.", bestSeller: true },
  { name: "Ombre Nomade", brand: "Louis Vuitton", gender: "Mixte", description: "Ambre profond, encens et oud fumé.", bestSeller: true },
  { name: "Light Blue Forever Pour Homme", brand: "Dolce & Gabbana", gender: "Homme", description: "Méditerranée fraîche éternelle." },
  { name: "Bitter Peach", brand: "Tom Ford", gender: "Mixte", description: "Pêche juteuse, rhum et cardamome." },
  { name: "Light Blue Forever Pour Femme", brand: "Dolce & Gabbana", gender: "Femme", description: "Citron de Sicile et néroli éternels." },
  { name: "Bare", brand: "Victoria's Secret", gender: "Femme", description: "Musc blanc sensuel et nu." },
  { name: "Ambre Nuit", brand: "Christian Dior", gender: "Mixte", description: "Rose Damascena et ambre nocturne." },
  { name: "Fève Délicieuse", brand: "Christian Dior", gender: "Mixte", description: "Fève tonka, praliné et vanille." },
  { name: "Lost Cherry", brand: "Tom Ford", gender: "Femme", description: "Cerise noire, amande et tonka.", bestSeller: true },
  { name: "Kirke", brand: "Tiziana Terenzi", gender: "Femme", description: "Fruits exotiques sorciers." },
  { name: "Amber Tigre", brand: "Givenchy", gender: "Mixte", description: "Ambre fauve, cuir et benjoin." },
  { name: "Rose d'Arabie", brand: "Armani Privé", gender: "Mixte", description: "Rose d'Orient, oud et safran." },
  { name: "Tobacco Oud", brand: "Tom Ford", gender: "Mixte", description: "Tabac riche et oud précieux." },
  { name: "Oud Wood", brand: "Tom Ford", gender: "Mixte", description: "Oud, bois de rose et santal.", bestSeller: true },
  { name: "Oud Ispahan", brand: "Christian Dior", gender: "Mixte", description: "Rose d'Ispahan et oud sacré." },
  { name: "Bois d'Argent", brand: "Christian Dior", gender: "Mixte", description: "Iris poudré et bois précieux." },
  { name: "Aventus", brand: "Creed", gender: "Homme", description: "Bouleau fumé et ananas iconique.", bestSeller: true },
  { name: "Black Orchid", brand: "Tom Ford", gender: "Mixte", description: "Orchidée noire, truffe et patchouli." },
  { name: "Silver Mountain Water", brand: "Creed", gender: "Mixte", description: "Frais alpin, thé vert et musc." },
  { name: "Gris Montaigne", brand: "Christian Dior", gender: "Femme", description: "Mandarine, rose et patchouli." },
  { name: "Soleil Blanc", brand: "Tom Ford", gender: "Mixte", description: "Tubéreuse solaire et noix de coco." },
];
const hommesSeeds = [
  { name: "Baccarat Rouge 540", brand: "Maison Francis Kurkdjian", gender: "Homme", description: "Safran, ambre gris et cèdre.", bestSeller: true },
  { name: "Stronger With You", brand: "Armani", gender: "Homme", description: "Cardamome, châtaigne et vanille." },
  { name: "Invictus Legend", brand: "Paco Rabanne", gender: "Homme", description: "Boisé aromatique légendaire." },
  { name: "Invictus Victory", brand: "Paco Rabanne", gender: "Homme", description: "Triomphe boisé doré et puissant." },
  { name: "Le Beau", brand: "Jean Paul Gaultier", gender: "Homme", description: "Coco, tonka et bois de santal." },
  { name: "Le Male Le Parfum", brand: "Jean Paul Gaultier", gender: "Homme", description: "Lavande, cardamome et vanille." },
  { name: "Bvlgari Man In Black", brand: "Bvlgari", gender: "Homme", description: "Rhum, tubéreuse et cuir." },
  { name: "Sauvage EDP", brand: "Christian Dior", gender: "Homme", description: "Bergamote vibrante et ambroxan.", bestSeller: true },
  { name: "Bleu de Chanel", brand: "Chanel", gender: "Homme", description: "Boisé aromatique, élégance masculine.", bestSeller: true },
  { name: "Lacoste Noir", brand: "Lacoste", gender: "Homme", description: "Boisé épicé moderne." },
  { name: "Sauvage", brand: "Christian Dior", gender: "Homme", description: "Bergamote et poivre sauvage." },
  { name: "1 Million", brand: "Paco Rabanne", gender: "Homme", description: "Cuir épicé, l'or liquide." },
  { name: "Invictus", brand: "Paco Rabanne", gender: "Homme", description: "Marine fraîche et boisée." },
  { name: "Lacoste Blanc", brand: "Lacoste", gender: "Homme", description: "Frais sportif et clean." },
  { name: "L'Homme", brand: "Yves Saint Laurent", gender: "Homme", description: "Boisé épicé moderne et chic." },
  { name: "Oud Bouquet", brand: "Lattafa", gender: "Mixte", description: "Bouquet d'oud raffiné et profond." },
  { name: "Y EDP", brand: "Yves Saint Laurent", gender: "Homme", description: "Pomme, sauge et fève tonka." },
  { name: "Terre d'Hermès", brand: "Hermès", gender: "Homme", description: "Pamplemousse, silex et vétiver.", bestSeller: true },
  { name: "La Nuit de l'Homme", brand: "Yves Saint Laurent", gender: "Homme", description: "Cardamome, lavande et cèdre." },
  { name: "Hugo Boss Bottled", brand: "Hugo Boss", gender: "Homme", description: "Pomme, cannelle et bois de santal." },
  { name: "King", brand: "Lattafa", gender: "Homme", description: "Oriental boisé royal et puissant." },
  { name: "Supreme Bouquet", brand: "Yves Saint Laurent", gender: "Homme", description: "Bouquet boisé suprême." },
  { name: "1 Million Elixir", brand: "Paco Rabanne", gender: "Homme", description: "Cardamome intense et cuir doré." },
  { name: "Scandal Pour Homme", brand: "Jean Paul Gaultier", gender: "Homme", description: "Caramel, miel et tabac." },
  { name: "Eros", brand: "Versace", gender: "Homme", description: "Menthe glaciale et vanille puissante.", bestSeller: true },
  { name: "Acqua di Giò", brand: "Armani", gender: "Homme", description: "Méditerranée fraîche et minérale." },
  { name: "Chrome", brand: "Azzaro", gender: "Homme", description: "Frais aquatique et lumineux." },
  { name: "212 VIP Men", brand: "Carolina Herrera", gender: "Homme", description: "Vodka, gin et cuir clubbing." },
  { name: "Silver Scent Intense", brand: "Jacques Bogart", gender: "Homme", description: "Boisé épicé argenté." },
  { name: "Lacoste Essential", brand: "Lacoste", gender: "Homme", description: "Vert aromatique essentiel." },
  { name: "Prada L'Homme", brand: "Prada", gender: "Homme", description: "Iris masculin élégant et moderne." },
  { name: "Just Cavalli Him", brand: "Roberto Cavalli", gender: "Homme", description: "Boisé aromatique sensuel." },
  { name: "Égoïste Platinum", brand: "Chanel", gender: "Homme", description: "Lavande, romarin et bois de santal." },
  { name: "L'Homme Idéal", brand: "Guerlain", gender: "Homme", description: "Amande gourmande et virile." },
  { name: "Mr. Burberry", brand: "Burberry", gender: "Homme", description: "Bergamote, cardamome et bois." },
  { name: "Lacoste Rouge", brand: "Lacoste", gender: "Homme", description: "Épicé chaleureux et viril." },
  { name: "Boss Bottled", brand: "Hugo Boss", gender: "Homme", description: "Classique masculin moderne." },
  { name: "1 Million Royal", brand: "Paco Rabanne", gender: "Homme", description: "Lavande sauge et bois ambré." },
  { name: "Armani Code", brand: "Armani", gender: "Homme", description: "Bergamote, fleur d'oranger et cuir." },
  { name: "Bad Boy", brand: "Carolina Herrera", gender: "Homme", description: "Cacao, sauge blanche et tonka." },
  { name: "Tight Oud", brand: "Lattafa", gender: "Mixte", description: "Oud serré, cuir et épices." },
  { name: "CK One", brand: "Calvin Klein", gender: "Mixte", description: "Frais agrumé minimaliste culte." },
  { name: "Possess Man", brand: "Oriflame", gender: "Homme", description: "Boisé envoûtant et magnétique." },
  { name: "Rochas Man", brand: "Rochas", gender: "Homme", description: "Café gourmand et lavande." },
  { name: "Tobacco Vanille", brand: "Tom Ford", gender: "Mixte", description: "Tabac riche, vanille et fruits secs.", bestSeller: true },
  { name: "Pi", brand: "Givenchy", gender: "Homme", description: "Vanille tonka et mandarine." },
  { name: "Royal Night", brand: "Lattafa", gender: "Homme", description: "Oriental nocturne royal." },
  { name: "L'Eau d'Issey Pour Homme", brand: "Issey Miyake", gender: "Homme", description: "Aquatique pur et minéral." },
  { name: "Polo Sport", brand: "Ralph Lauren", gender: "Homme", description: "Frais sportif énergique." },
  { name: "Phantom", brand: "Paco Rabanne", gender: "Homme", description: "Lavande, citron et musc boisé.", bestSeller: true },
  { name: "Fahrenheit", brand: "Christian Dior", gender: "Homme", description: "Violette, vétiver et notes pétrolières." },
  { name: "Gentleman", brand: "Givenchy", gender: "Homme", description: "Iris, patchouli et cuir noble." },
  { name: "Polo Blue", brand: "Ralph Lauren", gender: "Homme", description: "Mélon, basilic et suède frais." },
  { name: "The Dreamer", brand: "Versace", gender: "Homme", description: "Tabac, iris et bois de santal." },
  { name: "Allure Homme Sport", brand: "Chanel", gender: "Homme", description: "Citrus vif, vétiver et bois de santal." },
  { name: "Voyage d'Hermès", brand: "Hermès", gender: "Homme", description: "Cèdre, vétiver et herbe coupée." },
  { name: "Gucci Pour Homme", brand: "Gucci", gender: "Homme", description: "Cyprès, cèdre et cuir." },
  { name: "Guilty Pour Homme", brand: "Gucci", gender: "Homme", description: "Bergamote, cuir et vétiver." },
  { name: "Hugo", brand: "Hugo Boss", gender: "Homme", description: "Vert frais, résineux et boisé." },
  { name: "The Scent", brand: "Hugo Boss", gender: "Homme", description: "Gingembre, maniguette et cuir." },
  { name: "Acqua di Giò Profumo", brand: "Armani", gender: "Homme", description: "Marine, bergamote et encens." },
  { name: "Encre Noire", brand: "Lalique", gender: "Homme", description: "Vétiver intense et cèdre." },
  { name: "Cool Water", brand: "Davidoff", gender: "Homme", description: "Marine frais et aquatique classique." },
  { name: "Polo Black", brand: "Ralph Lauren", gender: "Homme", description: "Mangue, sauge et ambre." },
  { name: "The One", brand: "Dolce & Gabbana", gender: "Homme", description: "Gingembre, cardamome et cèdre." },
  { name: "Obsession Pour Homme", brand: "Calvin Klein", gender: "Homme", description: "Oriental vanille et santal." },
  { name: "Zino", brand: "Davidoff", gender: "Homme", description: "Boisé aromatique classique." },
  { name: "1 Million Lucky", brand: "Paco Rabanne", gender: "Homme", description: "Pamplemousse, haricot et patchouli." },
  { name: "Kouros", brand: "Yves Saint Laurent", gender: "Homme", description: "Chypre aromatique mythique." },
  { name: "Azzaro Pour Homme", brand: "Azzaro", gender: "Homme", description: "Lavande, anis et vétiver classique." },
  { name: "Bvlgari Aqva", brand: "Bvlgari", gender: "Homme", description: "Aquatique marin et hespéridé." },
  { name: "Declaration", brand: "Cartier", gender: "Homme", description: "Cardamome, cuir et cèdre élégant." },
];
const femmesSeeds = [
  { name: "The Only One", brand: "Dolce & Gabbana", gender: "Femme", description: "Café noir, fleur d'oranger et iris." },
  { name: "212 VIP", brand: "Carolina Herrera", gender: "Femme", description: "Rhum, fruit de la passion et musc." },
  { name: "Pure XS", brand: "Paco Rabanne", gender: "Femme", description: "Vanille, gingembre et néroli." },
  { name: "Bonbon", brand: "Viktor & Rolf", gender: "Femme", description: "Caramel solaire et joyeux." },
  { name: "Pure Musc", brand: "Narciso Rodriguez", gender: "Femme", description: "Musc blanc pur et lumineux.", bestSeller: true },
  { name: "Miss Dior Blooming Bouquet", brand: "Christian Dior", gender: "Femme", description: "Pivoine, rose et musc blanc." },
  { name: "L'Interdit Rouge", brand: "Givenchy", gender: "Femme", description: "Rose, tubéreuse et patchouli intense." },
  { name: "Scandal", brand: "Jean Paul Gaultier", gender: "Femme", description: "Miel, caramel et fleur d'oranger." },
  { name: "Coco Mademoiselle", brand: "Chanel", gender: "Femme", description: "Patchouli, rose et bergamote.", bestSeller: true },
  { name: "Escada Taj Sunset", brand: "Escada", gender: "Femme", description: "Mangue, fruit de la passion." },
  { name: "Évidence", brand: "Yves Rocher", gender: "Femme", description: "Rose, violette et musc tendre." },
  { name: "Coco Chanel", brand: "Chanel", gender: "Femme", description: "Oriental classique intemporel." },
  { name: "Le Parfum Royal", brand: "Elie Saab", gender: "Femme", description: "Fleur d'oranger, jasmin et patchouli." },
  { name: "L'Interdit", brand: "Givenchy", gender: "Femme", description: "Tubéreuse blanche et vétiver noir." },
  { name: "L'Instant de Guerlain", brand: "Guerlain", gender: "Femme", description: "Magnolia, miel et ambre." },
  { name: "Incandessence", brand: "Avon", gender: "Femme", description: "Floral lumineux et solaire." },
  { name: "La Nuit Trésor", brand: "Lancôme", gender: "Femme", description: "Praline, rose et vanille noire.", bestSeller: true },
  { name: "Amber Elixir", brand: "Oriflame", gender: "Femme", description: "Ambre, vanille et fève tonka." },
  { name: "Eclat Femme", brand: "Oriflame", gender: "Femme", description: "Floral cristallin et lumineux." },
  { name: "Enigma", brand: "Oriflame", gender: "Femme", description: "Pomme caramélisée et cardamome." },
  { name: "Giordani Gold", brand: "Oriflame", gender: "Femme", description: "Or floral riche et précieux." },
  { name: "Black Opium", brand: "Yves Saint Laurent", gender: "Femme", description: "Café noir, vanille et fleurs blanches.", bestSeller: true },
  { name: "Mon Paris", brand: "Yves Saint Laurent", gender: "Femme", description: "Framboise, pivoine et patchouli." },
  { name: "Libre", brand: "Yves Saint Laurent", gender: "Femme", description: "Lavande française et fleur d'oranger." },
  { name: "La Vie Est Belle", brand: "Lancôme", gender: "Femme", description: "Iris, praline et fève tonka.", bestSeller: true },
  { name: "Idôle", brand: "Lancôme", gender: "Femme", description: "Bergamote, rose et musc." },
  { name: "Si", brand: "Giorgio Armani", gender: "Femme", description: "Cassis, iris et patchouli." },
  { name: "Si Passione", brand: "Giorgio Armani", gender: "Femme", description: "Poire, rose et patchouli." },
  { name: "Good Girl", brand: "Carolina Herrera", gender: "Femme", description: "Jasmin, amande et vanille.", bestSeller: true },
  { name: "Very Good Girl", brand: "Carolina Herrera", gender: "Femme", description: "Litchi, rose et musc." },
  { name: "Miss Dior", brand: "Christian Dior", gender: "Femme", description: "Musc, pivoine et groseille." },
  { name: "J'adore", brand: "Christian Dior", gender: "Femme", description: "Ylang-ylang, rose et magnolia.", bestSeller: true },
  { name: "Hypnotic Poison", brand: "Christian Dior", gender: "Femme", description: "Amande, vanille et musc enchanteur." },
  { name: "Flowerbomb", brand: "Viktor & Rolf", gender: "Femme", description: "Jasmin, rose et patchouli explosif.", bestSeller: true },
  { name: "Crystal Noir", brand: "Versace", gender: "Femme", description: "Gardénia, noix de coco et ambre." },
  { name: "Bright Crystal", brand: "Versace", gender: "Femme", description: "Pivoine, magnolia et musc frais." },
  { name: "Eros Pour Femme", brand: "Versace", gender: "Femme", description: "Grenade, citron et pamplemousse." },
  { name: "Narciso Rodriguez For Her", brand: "Narciso Rodriguez", gender: "Femme", description: "Musc sensuel et fleur d'oranger." },
  { name: "Candy", brand: "Prada", gender: "Femme", description: "Caramel, vanille et benjoin doux." },
  { name: "Alien", brand: "Thierry Mugler", gender: "Femme", description: "Jasmin solaire et bois de cachemire.", bestSeller: true },
  { name: "Angel", brand: "Thierry Mugler", gender: "Femme", description: "Patchouli, miel et vanille mythique." },
  { name: "Euphoria", brand: "Calvin Klein", gender: "Femme", description: "Grenade, kaki et orchidée." },
  { name: "Her", brand: "Burberry", gender: "Femme", description: "Fraise, framboise et jasmin vibrant." },
  { name: "Daisy", brand: "Marc Jacobs", gender: "Femme", description: "Fraise, violette et jasmin champêtre." },
  { name: "Be Delicious", brand: "DKNY", gender: "Femme", description: "Pomme verte, magnolia et musc blanc." },
  { name: "Amor Amor", brand: "Cacharel", gender: "Femme", description: "Pamplemousse, violette et musc rose." },
  { name: "Chance Eau Tendre", brand: "Chanel", gender: "Femme", description: "Grapefruit, jasmin et musc délicat." },
  { name: "Chance", brand: "Chanel", gender: "Femme", description: "Citrus, jasmin et patchouli frais." },
  { name: "N°5", brand: "Chanel", gender: "Femme", description: "Aldéhyde, rose et ylang-ylang mythique." },
  { name: "Mon Guerlain", brand: "Guerlain", gender: "Femme", description: "Lavande, bergamote et vanille gourmande." },
  { name: "La Petite Robe Noire", brand: "Guerlain", gender: "Femme", description: "Thé noir, cerise et rose." },
  { name: "Donna Born In Roma", brand: "Valentino", gender: "Femme", description: "Iris, vanille et bois de santal." },
  { name: "Alive", brand: "Hugo Boss", gender: "Femme", description: "Pomme, jasmin et bois ambré." },
  { name: "L'Eau d'Issey", brand: "Issey Miyake", gender: "Femme", description: "Lotus, musc et bois de rose." },
  { name: "212 Sexy", brand: "Carolina Herrera", gender: "Femme", description: "Mandarine, jasmin et musc sensuel." },
  { name: "Pure Poison", brand: "Christian Dior", gender: "Femme", description: "Jasmin blanc, orange et santal." },
  { name: "Addict", brand: "Christian Dior", gender: "Femme", description: "Vanille et magnolia envoûtants." },
  { name: "Gucci Bloom", brand: "Gucci", gender: "Femme", description: "Jasmin, rose et gardénia naturel." },
  { name: "Guilty Pour Femme", brand: "Gucci", gender: "Femme", description: "Pêche, mandarine et jasmin." },
  { name: "Pleasures", brand: "Estée Lauder", gender: "Femme", description: "Rose, lilas et patchouli printanier." },
  { name: "Beautiful", brand: "Estée Lauder", gender: "Femme", description: "Rose, jasmin et musc élégant." },
  { name: "Rose Rush", brand: "Lattafa", gender: "Femme", description: "Rose, musc et vanille légère." },
  { name: "Yara", brand: "Lattafa", gender: "Femme", description: "Pêche, jasmin et musc rose.", bestSeller: true },
  { name: "Hayati", brand: "Rasasi", gender: "Femme", description: "Floral doux et musqué oriental." },
  { name: "Khizana", brand: "Al Haramain", gender: "Femme", description: "Rose et musc envoûtants." },
  { name: "Mayar", brand: "Swiss Arabian", gender: "Femme", description: "Floral oriental délicat." },
];
const orientauxSeeds = [
  { name: "Oud Maknoon", brand: "Lattafa", gender: "Mixte", description: "Oud profond, safran et ambre royal.", bestSeller: true },
  { name: "Asad", brand: "Lattafa", gender: "Homme", description: "Citrus vif, boisé et musc puissant." },
  { name: "Badee Al Oud Amethyst", brand: "Lattafa", gender: "Mixte", description: "Oud violet, fruits exotiques et vanille." },
  { name: "Ana Abiyedh Parfum", brand: "Lattafa", gender: "Femme", description: "Musc blanc pur, oud et rose." },
  { name: "Yara Tous", brand: "Lattafa", gender: "Mixte", description: "Rose, musc et notes fruitées douces." },
  { name: "Oud Mood Reminiscence", brand: "Lattafa", gender: "Mixte", description: "Oud, rose et ambre enveloppants." },
  { name: "Ameer Al Oud", brand: "Lattafa", gender: "Mixte", description: "Oud intense et royal, musc et santal." },
  { name: "Raghba Wood Intense", brand: "Lattafa", gender: "Mixte", description: "Bois d'oud intense et résineux." },
  { name: "Qafiya 95", brand: "Swiss Arabian", gender: "Homme", description: "Oud, encens et musc oriental profond." },
  { name: "Shaghaf Oud Aswad", brand: "Swiss Arabian", gender: "Mixte", description: "Oud noir, rose ambré et épices.", bestSeller: true },
  { name: "Ghawali", brand: "Swiss Arabian", gender: "Femme", description: "Floral oriental précieux et délicat." },
  { name: "Tharwah Gold", brand: "Swiss Arabian", gender: "Homme", description: "Oud royal, safran et notes boisées." },
  { name: "Bait Al Bakhoor", brand: "Swiss Arabian", gender: "Mixte", description: "Encens traditionnel, oud et santal." },
  { name: "Amber Oud Tobacco Edition", brand: "Al Haramain", gender: "Mixte", description: "Ambre riche, tabac blond et oud.", bestSeller: true },
  { name: "Amber Oud Gold Edition", brand: "Al Haramain", gender: "Mixte", description: "Ambre somptueux et oud précieux." },
  { name: "All The Money", brand: "Al Haramain", gender: "Homme", description: "Citrus vif, boisé et musc luxueux." },
  { name: "Musk Tahara", brand: "Al Haramain", gender: "Femme", description: "Musc blanc pur et poudré." },
  { name: "Oud Cambodi", brand: "Al Haramain", gender: "Mixte", description: "Oud du Cambodge pur et résineux." },
  { name: "La Yuqawam Pour Homme", brand: "Rasasi", gender: "Homme", description: "Oud intense, rose et ambre oriental." },
  { name: "Dakhon", brand: "Rasasi", gender: "Mixte", description: "Fumé, oud profond et ambré." },
  { name: "Faris", brand: "Rasasi", gender: "Homme", description: "Boisé épicé arabe et cuir." },
  { name: "Egra", brand: "Rasasi", gender: "Mixte", description: "Floral oriental délicat et musqué." },
  { name: "Mukhallat Malaki", brand: "Rasasi", gender: "Mixte", description: "Mélange royal arabe, oud et épices." },
  { name: "Daw Al Oud", brand: "Ajmal", gender: "Mixte", description: "Lumière d'oud, jasmin et ambre." },
  { name: "Evoke Gold", brand: "Ajmal", gender: "Homme", description: "Oud, cuir et ambre sophistiqués." },
  { name: "Barakkat Rouge 540", brand: "Fragrance World", gender: "Mixte", description: "Safran, ambre et oud somptueux.", bestSeller: true },
  { name: "Club de Nuit Intense Man", brand: "Armaf", gender: "Homme", description: "Oud, bergamote et cuir intense.", bestSeller: true },
  { name: "Club de Nuit Intense Woman", brand: "Armaf", gender: "Femme", description: "Floral fruité et boisé élégant." },
  { name: "Golden Oud", brand: "Armaf", gender: "Mixte", description: "Oud doré, santal et épices chaudes." },
  { name: "Oud For Glory", brand: "Maison Oud", gender: "Mixte", description: "Oud noble, rose et ambre précieux." },
  { name: "Rose Oud", brand: "Nusuk", gender: "Mixte", description: "Rose épanouie et oud harmonieux." },
  { name: "Oud Safi", brand: "Nusuk", gender: "Mixte", description: "Oud pur, bois de santal et musc." },
  { name: "Oud Al Layl", brand: "Arabian Oud", gender: "Mixte", description: "Oud nocturne, encens et ambre." },
  { name: "Kalemat", brand: "Arabian Oud", gender: "Mixte", description: "Ambre noir, oud fumé et musc.", bestSeller: true },
  { name: "Rouat Al Oud", brand: "Arabian Oud", gender: "Homme", description: "Oud majestueux et boisé oriental." },
];

const esc = (s) => String(s).replace(/\\/g, '\\\\').replace(/'/g, "''");

const COLS = "(name, brand, category, gender, price, description, image_url, best_seller, sort_order, scent, stock_status)";

function makeInsert(seeds, cat, offset) {
  const rows = seeds.map((p, i) => {
    const bs = p.bestSeller ? 'true' : 'false';
    return `('${esc(p.name)}','${esc(p.brand)}','${cat}','${p.gender}',50,'${esc(p.description)}','',${bs},${offset+i},'frais','in_stock')`;
  });
  return `INSERT INTO perfumes ${COLS}\nVALUES\n${rows.join(',\n')};`;
}

const sql = `-- Import all perfumes – run each block separately if one fails
-- SQL Editor: https://supabase.com/dashboard/project/thlcfenfphvbypqplvci/sql

-- ============================================================
-- BLOCK 1: NICHE (${nicheSeeds.length} parfums)
-- ============================================================
${makeInsert(nicheSeeds, 'NICHE', 0)}

-- ============================================================
-- BLOCK 2: HOMMES (${hommesSeeds.length} parfums)
-- ============================================================
${makeInsert(hommesSeeds, 'HOMMES', nicheSeeds.length)}

-- ============================================================
-- BLOCK 3: FEMMES (${femmesSeeds.length} parfums)
-- ============================================================
${makeInsert(femmesSeeds, 'FEMMES', nicheSeeds.length + hommesSeeds.length)}

-- ============================================================
-- BLOCK 4: ORIENTAUX (${orientauxSeeds.length} parfums)
-- ============================================================
${makeInsert(orientauxSeeds, 'ORIENTAUX', nicheSeeds.length + hommesSeeds.length + femmesSeeds.length)}
`;

import { writeFileSync } from 'fs';
writeFileSync('./scripts/import-perfumes.sql', sql);
const total = nicheSeeds.length + hommesSeeds.length + femmesSeeds.length + orientauxSeeds.length;
console.log(`Generated SQL with ${total} perfumes in 4 blocks -> scripts/import-perfumes.sql`);
