-- Import all perfumes – run each block separately if one fails
-- SQL Editor: https://supabase.com/dashboard/project/thlcfenfphvbypqplvci/sql

-- ============================================================
-- BLOCK 1: NICHE (47 parfums)
-- ============================================================
INSERT INTO perfumes (name, brand, category, gender, price, description, image_url, best_seller, sort_order, scent, stock_status)
VALUES
('Rouge Malachite','Armani Privé','NICHE','Mixte',50,'Oriental boisé profond et précieux.','',false,0,'frais','in_stock'),
('Verte Malachite','Armani Privé','NICHE','Mixte',50,'Émeraude végétale rare et raffinée.','',false,1,'frais','in_stock'),
('Cuir Beluga','Guerlain','NICHE','Mixte',50,'Cuir velouté, vanille et héliotrope.','',false,2,'frais','in_stock'),
('Montale Roses Musk','Montale','NICHE','Femme',50,'Roses opulentes sur lit de musc blanc.','',false,3,'frais','in_stock'),
('Red Oud','Montale','NICHE','Mixte',50,'Oud rouge intense et résineux.','',true,4,'frais','in_stock'),
('Black Oud','Montale','NICHE','Mixte',50,'Oud noir mystérieux et boisé.','',false,5,'frais','in_stock'),
('Fleur Narcotique','Nishane','NICHE','Mixte',50,'Floral fruité hypnotique culte.','',true,6,'frais','in_stock'),
('Fucking Fabulous','Tom Ford','NICHE','Mixte',50,'Cuir, amande et lavande iconique.','',false,7,'frais','in_stock'),
('Joop! Homme','Joop!','NICHE','Homme',50,'Oriental fleuri rouge mythique.','',false,8,'frais','in_stock'),
('Pegasus','Parfums de Marly','NICHE','Homme',50,'Amande, héliotrope et vanille luxueux.','',false,9,'frais','in_stock'),
('Noir de Noir','Tom Ford','NICHE','Mixte',50,'Rose noire, truffe et patchouli.','',false,10,'frais','in_stock'),
('Erba Pura','Xerjoff','NICHE','Mixte',50,'Fruité méditerranéen ultra raffiné.','',true,11,'frais','in_stock'),
('Tom Ford Noir Extreme','Tom Ford','NICHE','Homme',50,'Oriental gourmand sophistiqué.','',false,12,'frais','in_stock'),
('Le Parfum Mercedes-Benz','Mercedes-Benz','NICHE','Homme',50,'Boisé chypré moderne et élégant.','',false,13,'frais','in_stock'),
('Sunshine','Amouage','NICHE','Femme',50,'Solaire, gourmand et radieux.','',false,14,'frais','in_stock'),
('Alexandria II','Xerjoff','NICHE','Mixte',50,'Oud miellé, ambré et vanille rare.','',false,15,'frais','in_stock'),
('Métallique','Tom Ford','NICHE','Mixte',50,'Lavande poudrée et fleur d''oranger.','',false,16,'frais','in_stock'),
('Cartier La Panthère','Cartier','NICHE','Femme',50,'Chypre floral félin et magnétique.','',false,17,'frais','in_stock'),
('Mandarino di Amalfi','Tom Ford','NICHE','Mixte',50,'Mandarine de Sicile lumineuse.','',false,18,'frais','in_stock'),
('Yellow Diamond Intense','Versace','NICHE','Femme',50,'Floral fruité scintillant.','',false,19,'frais','in_stock'),
('Coco Vanille','Mancera','NICHE','Mixte',50,'Coco crémeux, vanille et oud doux.','',true,20,'frais','in_stock'),
('Dolce & Gabbana The One','Dolce & Gabbana','NICHE','Femme',50,'Oriental floral chaleureux.','',false,21,'frais','in_stock'),
('Costa Azzurra','Tom Ford','NICHE','Mixte',50,'Évasion marine méditerranéenne.','',false,22,'frais','in_stock'),
('Stronger With You Amber','Armani','NICHE','Homme',50,'Ambre, miel et tabac magnétique.','',false,23,'frais','in_stock'),
('Aïsha','Christian Dior','NICHE','Femme',50,'Floral oriental précieux.','',false,24,'frais','in_stock'),
('Attrape-Rêves','Louis Vuitton','NICHE','Femme',50,'Pêche solaire, jasmin et caramel.','',false,25,'frais','in_stock'),
('Ombré Leather','Tom Ford','NICHE','Mixte',50,'Cuir suédé et fleur de patchouli.','',true,26,'frais','in_stock'),
('Ombre Nomade','Louis Vuitton','NICHE','Mixte',50,'Ambre profond, encens et oud fumé.','',true,27,'frais','in_stock'),
('Light Blue Forever Pour Homme','Dolce & Gabbana','NICHE','Homme',50,'Méditerranée fraîche éternelle.','',false,28,'frais','in_stock'),
('Bitter Peach','Tom Ford','NICHE','Mixte',50,'Pêche juteuse, rhum et cardamome.','',false,29,'frais','in_stock'),
('Light Blue Forever Pour Femme','Dolce & Gabbana','NICHE','Femme',50,'Citron de Sicile et néroli éternels.','',false,30,'frais','in_stock'),
('Bare','Victoria''s Secret','NICHE','Femme',50,'Musc blanc sensuel et nu.','',false,31,'frais','in_stock'),
('Ambre Nuit','Christian Dior','NICHE','Mixte',50,'Rose Damascena et ambre nocturne.','',false,32,'frais','in_stock'),
('Fève Délicieuse','Christian Dior','NICHE','Mixte',50,'Fève tonka, praliné et vanille.','',false,33,'frais','in_stock'),
('Lost Cherry','Tom Ford','NICHE','Femme',50,'Cerise noire, amande et tonka.','',true,34,'frais','in_stock'),
('Kirke','Tiziana Terenzi','NICHE','Femme',50,'Fruits exotiques sorciers.','',false,35,'frais','in_stock'),
('Amber Tigre','Givenchy','NICHE','Mixte',50,'Ambre fauve, cuir et benjoin.','',false,36,'frais','in_stock'),
('Rose d''Arabie','Armani Privé','NICHE','Mixte',50,'Rose d''Orient, oud et safran.','',false,37,'frais','in_stock'),
('Tobacco Oud','Tom Ford','NICHE','Mixte',50,'Tabac riche et oud précieux.','',false,38,'frais','in_stock'),
('Oud Wood','Tom Ford','NICHE','Mixte',50,'Oud, bois de rose et santal.','',true,39,'frais','in_stock'),
('Oud Ispahan','Christian Dior','NICHE','Mixte',50,'Rose d''Ispahan et oud sacré.','',false,40,'frais','in_stock'),
('Bois d''Argent','Christian Dior','NICHE','Mixte',50,'Iris poudré et bois précieux.','',false,41,'frais','in_stock'),
('Aventus','Creed','NICHE','Homme',50,'Bouleau fumé et ananas iconique.','',true,42,'frais','in_stock'),
('Black Orchid','Tom Ford','NICHE','Mixte',50,'Orchidée noire, truffe et patchouli.','',false,43,'frais','in_stock'),
('Silver Mountain Water','Creed','NICHE','Mixte',50,'Frais alpin, thé vert et musc.','',false,44,'frais','in_stock'),
('Gris Montaigne','Christian Dior','NICHE','Femme',50,'Mandarine, rose et patchouli.','',false,45,'frais','in_stock'),
('Soleil Blanc','Tom Ford','NICHE','Mixte',50,'Tubéreuse solaire et noix de coco.','',false,46,'frais','in_stock');

-- ============================================================
-- BLOCK 2: HOMMES (72 parfums)
-- ============================================================
INSERT INTO perfumes (name, brand, category, gender, price, description, image_url, best_seller, sort_order, scent, stock_status)
VALUES
('Baccarat Rouge 540','Maison Francis Kurkdjian','HOMMES','Homme',50,'Safran, ambre gris et cèdre.','',true,47,'frais','in_stock'),
('Stronger With You','Armani','HOMMES','Homme',50,'Cardamome, châtaigne et vanille.','',false,48,'frais','in_stock'),
('Invictus Legend','Paco Rabanne','HOMMES','Homme',50,'Boisé aromatique légendaire.','',false,49,'frais','in_stock'),
('Invictus Victory','Paco Rabanne','HOMMES','Homme',50,'Triomphe boisé doré et puissant.','',false,50,'frais','in_stock'),
('Le Beau','Jean Paul Gaultier','HOMMES','Homme',50,'Coco, tonka et bois de santal.','',false,51,'frais','in_stock'),
('Le Male Le Parfum','Jean Paul Gaultier','HOMMES','Homme',50,'Lavande, cardamome et vanille.','',false,52,'frais','in_stock'),
('Bvlgari Man In Black','Bvlgari','HOMMES','Homme',50,'Rhum, tubéreuse et cuir.','',false,53,'frais','in_stock'),
('Sauvage EDP','Christian Dior','HOMMES','Homme',50,'Bergamote vibrante et ambroxan.','',true,54,'frais','in_stock'),
('Bleu de Chanel','Chanel','HOMMES','Homme',50,'Boisé aromatique, élégance masculine.','',true,55,'frais','in_stock'),
('Lacoste Noir','Lacoste','HOMMES','Homme',50,'Boisé épicé moderne.','',false,56,'frais','in_stock'),
('Sauvage','Christian Dior','HOMMES','Homme',50,'Bergamote et poivre sauvage.','',false,57,'frais','in_stock'),
('1 Million','Paco Rabanne','HOMMES','Homme',50,'Cuir épicé, l''or liquide.','',false,58,'frais','in_stock'),
('Invictus','Paco Rabanne','HOMMES','Homme',50,'Marine fraîche et boisée.','',false,59,'frais','in_stock'),
('Lacoste Blanc','Lacoste','HOMMES','Homme',50,'Frais sportif et clean.','',false,60,'frais','in_stock'),
('L''Homme','Yves Saint Laurent','HOMMES','Homme',50,'Boisé épicé moderne et chic.','',false,61,'frais','in_stock'),
('Oud Bouquet','Lattafa','HOMMES','Mixte',50,'Bouquet d''oud raffiné et profond.','',false,62,'frais','in_stock'),
('Y EDP','Yves Saint Laurent','HOMMES','Homme',50,'Pomme, sauge et fève tonka.','',false,63,'frais','in_stock'),
('Terre d''Hermès','Hermès','HOMMES','Homme',50,'Pamplemousse, silex et vétiver.','',true,64,'frais','in_stock'),
('La Nuit de l''Homme','Yves Saint Laurent','HOMMES','Homme',50,'Cardamome, lavande et cèdre.','',false,65,'frais','in_stock'),
('Hugo Boss Bottled','Hugo Boss','HOMMES','Homme',50,'Pomme, cannelle et bois de santal.','',false,66,'frais','in_stock'),
('King','Lattafa','HOMMES','Homme',50,'Oriental boisé royal et puissant.','',false,67,'frais','in_stock'),
('Supreme Bouquet','Yves Saint Laurent','HOMMES','Homme',50,'Bouquet boisé suprême.','',false,68,'frais','in_stock'),
('1 Million Elixir','Paco Rabanne','HOMMES','Homme',50,'Cardamome intense et cuir doré.','',false,69,'frais','in_stock'),
('Scandal Pour Homme','Jean Paul Gaultier','HOMMES','Homme',50,'Caramel, miel et tabac.','',false,70,'frais','in_stock'),
('Eros','Versace','HOMMES','Homme',50,'Menthe glaciale et vanille puissante.','',true,71,'frais','in_stock'),
('Acqua di Giò','Armani','HOMMES','Homme',50,'Méditerranée fraîche et minérale.','',false,72,'frais','in_stock'),
('Chrome','Azzaro','HOMMES','Homme',50,'Frais aquatique et lumineux.','',false,73,'frais','in_stock'),
('212 VIP Men','Carolina Herrera','HOMMES','Homme',50,'Vodka, gin et cuir clubbing.','',false,74,'frais','in_stock'),
('Silver Scent Intense','Jacques Bogart','HOMMES','Homme',50,'Boisé épicé argenté.','',false,75,'frais','in_stock'),
('Lacoste Essential','Lacoste','HOMMES','Homme',50,'Vert aromatique essentiel.','',false,76,'frais','in_stock'),
('Prada L''Homme','Prada','HOMMES','Homme',50,'Iris masculin élégant et moderne.','',false,77,'frais','in_stock'),
('Just Cavalli Him','Roberto Cavalli','HOMMES','Homme',50,'Boisé aromatique sensuel.','',false,78,'frais','in_stock'),
('Égoïste Platinum','Chanel','HOMMES','Homme',50,'Lavande, romarin et bois de santal.','',false,79,'frais','in_stock'),
('L''Homme Idéal','Guerlain','HOMMES','Homme',50,'Amande gourmande et virile.','',false,80,'frais','in_stock'),
('Mr. Burberry','Burberry','HOMMES','Homme',50,'Bergamote, cardamome et bois.','',false,81,'frais','in_stock'),
('Lacoste Rouge','Lacoste','HOMMES','Homme',50,'Épicé chaleureux et viril.','',false,82,'frais','in_stock'),
('Boss Bottled','Hugo Boss','HOMMES','Homme',50,'Classique masculin moderne.','',false,83,'frais','in_stock'),
('1 Million Royal','Paco Rabanne','HOMMES','Homme',50,'Lavande sauge et bois ambré.','',false,84,'frais','in_stock'),
('Armani Code','Armani','HOMMES','Homme',50,'Bergamote, fleur d''oranger et cuir.','',false,85,'frais','in_stock'),
('Bad Boy','Carolina Herrera','HOMMES','Homme',50,'Cacao, sauge blanche et tonka.','',false,86,'frais','in_stock'),
('Tight Oud','Lattafa','HOMMES','Mixte',50,'Oud serré, cuir et épices.','',false,87,'frais','in_stock'),
('CK One','Calvin Klein','HOMMES','Mixte',50,'Frais agrumé minimaliste culte.','',false,88,'frais','in_stock'),
('Possess Man','Oriflame','HOMMES','Homme',50,'Boisé envoûtant et magnétique.','',false,89,'frais','in_stock'),
('Rochas Man','Rochas','HOMMES','Homme',50,'Café gourmand et lavande.','',false,90,'frais','in_stock'),
('Tobacco Vanille','Tom Ford','HOMMES','Mixte',50,'Tabac riche, vanille et fruits secs.','',true,91,'frais','in_stock'),
('Pi','Givenchy','HOMMES','Homme',50,'Vanille tonka et mandarine.','',false,92,'frais','in_stock'),
('Royal Night','Lattafa','HOMMES','Homme',50,'Oriental nocturne royal.','',false,93,'frais','in_stock'),
('L''Eau d''Issey Pour Homme','Issey Miyake','HOMMES','Homme',50,'Aquatique pur et minéral.','',false,94,'frais','in_stock'),
('Polo Sport','Ralph Lauren','HOMMES','Homme',50,'Frais sportif énergique.','',false,95,'frais','in_stock'),
('Phantom','Paco Rabanne','HOMMES','Homme',50,'Lavande, citron et musc boisé.','',true,96,'frais','in_stock'),
('Fahrenheit','Christian Dior','HOMMES','Homme',50,'Violette, vétiver et notes pétrolières.','',false,97,'frais','in_stock'),
('Gentleman','Givenchy','HOMMES','Homme',50,'Iris, patchouli et cuir noble.','',false,98,'frais','in_stock'),
('Polo Blue','Ralph Lauren','HOMMES','Homme',50,'Mélon, basilic et suède frais.','',false,99,'frais','in_stock'),
('The Dreamer','Versace','HOMMES','Homme',50,'Tabac, iris et bois de santal.','',false,100,'frais','in_stock'),
('Allure Homme Sport','Chanel','HOMMES','Homme',50,'Citrus vif, vétiver et bois de santal.','',false,101,'frais','in_stock'),
('Voyage d''Hermès','Hermès','HOMMES','Homme',50,'Cèdre, vétiver et herbe coupée.','',false,102,'frais','in_stock'),
('Gucci Pour Homme','Gucci','HOMMES','Homme',50,'Cyprès, cèdre et cuir.','',false,103,'frais','in_stock'),
('Guilty Pour Homme','Gucci','HOMMES','Homme',50,'Bergamote, cuir et vétiver.','',false,104,'frais','in_stock'),
('Hugo','Hugo Boss','HOMMES','Homme',50,'Vert frais, résineux et boisé.','',false,105,'frais','in_stock'),
('The Scent','Hugo Boss','HOMMES','Homme',50,'Gingembre, maniguette et cuir.','',false,106,'frais','in_stock'),
('Acqua di Giò Profumo','Armani','HOMMES','Homme',50,'Marine, bergamote et encens.','',false,107,'frais','in_stock'),
('Encre Noire','Lalique','HOMMES','Homme',50,'Vétiver intense et cèdre.','',false,108,'frais','in_stock'),
('Cool Water','Davidoff','HOMMES','Homme',50,'Marine frais et aquatique classique.','',false,109,'frais','in_stock'),
('Polo Black','Ralph Lauren','HOMMES','Homme',50,'Mangue, sauge et ambre.','',false,110,'frais','in_stock'),
('The One','Dolce & Gabbana','HOMMES','Homme',50,'Gingembre, cardamome et cèdre.','',false,111,'frais','in_stock'),
('Obsession Pour Homme','Calvin Klein','HOMMES','Homme',50,'Oriental vanille et santal.','',false,112,'frais','in_stock'),
('Zino','Davidoff','HOMMES','Homme',50,'Boisé aromatique classique.','',false,113,'frais','in_stock'),
('1 Million Lucky','Paco Rabanne','HOMMES','Homme',50,'Pamplemousse, haricot et patchouli.','',false,114,'frais','in_stock'),
('Kouros','Yves Saint Laurent','HOMMES','Homme',50,'Chypre aromatique mythique.','',false,115,'frais','in_stock'),
('Azzaro Pour Homme','Azzaro','HOMMES','Homme',50,'Lavande, anis et vétiver classique.','',false,116,'frais','in_stock'),
('Bvlgari Aqva','Bvlgari','HOMMES','Homme',50,'Aquatique marin et hespéridé.','',false,117,'frais','in_stock'),
('Declaration','Cartier','HOMMES','Homme',50,'Cardamome, cuir et cèdre élégant.','',false,118,'frais','in_stock');

-- ============================================================
-- BLOCK 3: FEMMES (66 parfums)
-- ============================================================
INSERT INTO perfumes (name, brand, category, gender, price, description, image_url, best_seller, sort_order, scent, stock_status)
VALUES
('The Only One','Dolce & Gabbana','FEMMES','Femme',50,'Café noir, fleur d''oranger et iris.','',false,119,'frais','in_stock'),
('212 VIP','Carolina Herrera','FEMMES','Femme',50,'Rhum, fruit de la passion et musc.','',false,120,'frais','in_stock'),
('Pure XS','Paco Rabanne','FEMMES','Femme',50,'Vanille, gingembre et néroli.','',false,121,'frais','in_stock'),
('Bonbon','Viktor & Rolf','FEMMES','Femme',50,'Caramel solaire et joyeux.','',false,122,'frais','in_stock'),
('Pure Musc','Narciso Rodriguez','FEMMES','Femme',50,'Musc blanc pur et lumineux.','',true,123,'frais','in_stock'),
('Miss Dior Blooming Bouquet','Christian Dior','FEMMES','Femme',50,'Pivoine, rose et musc blanc.','',false,124,'frais','in_stock'),
('L''Interdit Rouge','Givenchy','FEMMES','Femme',50,'Rose, tubéreuse et patchouli intense.','',false,125,'frais','in_stock'),
('Scandal','Jean Paul Gaultier','FEMMES','Femme',50,'Miel, caramel et fleur d''oranger.','',false,126,'frais','in_stock'),
('Coco Mademoiselle','Chanel','FEMMES','Femme',50,'Patchouli, rose et bergamote.','',true,127,'frais','in_stock'),
('Escada Taj Sunset','Escada','FEMMES','Femme',50,'Mangue, fruit de la passion.','',false,128,'frais','in_stock'),
('Évidence','Yves Rocher','FEMMES','Femme',50,'Rose, violette et musc tendre.','',false,129,'frais','in_stock'),
('Coco Chanel','Chanel','FEMMES','Femme',50,'Oriental classique intemporel.','',false,130,'frais','in_stock'),
('Le Parfum Royal','Elie Saab','FEMMES','Femme',50,'Fleur d''oranger, jasmin et patchouli.','',false,131,'frais','in_stock'),
('L''Interdit','Givenchy','FEMMES','Femme',50,'Tubéreuse blanche et vétiver noir.','',false,132,'frais','in_stock'),
('L''Instant de Guerlain','Guerlain','FEMMES','Femme',50,'Magnolia, miel et ambre.','',false,133,'frais','in_stock'),
('Incandessence','Avon','FEMMES','Femme',50,'Floral lumineux et solaire.','',false,134,'frais','in_stock'),
('La Nuit Trésor','Lancôme','FEMMES','Femme',50,'Praline, rose et vanille noire.','',true,135,'frais','in_stock'),
('Amber Elixir','Oriflame','FEMMES','Femme',50,'Ambre, vanille et fève tonka.','',false,136,'frais','in_stock'),
('Eclat Femme','Oriflame','FEMMES','Femme',50,'Floral cristallin et lumineux.','',false,137,'frais','in_stock'),
('Enigma','Oriflame','FEMMES','Femme',50,'Pomme caramélisée et cardamome.','',false,138,'frais','in_stock'),
('Giordani Gold','Oriflame','FEMMES','Femme',50,'Or floral riche et précieux.','',false,139,'frais','in_stock'),
('Black Opium','Yves Saint Laurent','FEMMES','Femme',50,'Café noir, vanille et fleurs blanches.','',true,140,'frais','in_stock'),
('Mon Paris','Yves Saint Laurent','FEMMES','Femme',50,'Framboise, pivoine et patchouli.','',false,141,'frais','in_stock'),
('Libre','Yves Saint Laurent','FEMMES','Femme',50,'Lavande française et fleur d''oranger.','',false,142,'frais','in_stock'),
('La Vie Est Belle','Lancôme','FEMMES','Femme',50,'Iris, praline et fève tonka.','',true,143,'frais','in_stock'),
('Idôle','Lancôme','FEMMES','Femme',50,'Bergamote, rose et musc.','',false,144,'frais','in_stock'),
('Si','Giorgio Armani','FEMMES','Femme',50,'Cassis, iris et patchouli.','',false,145,'frais','in_stock'),
('Si Passione','Giorgio Armani','FEMMES','Femme',50,'Poire, rose et patchouli.','',false,146,'frais','in_stock'),
('Good Girl','Carolina Herrera','FEMMES','Femme',50,'Jasmin, amande et vanille.','',true,147,'frais','in_stock'),
('Very Good Girl','Carolina Herrera','FEMMES','Femme',50,'Litchi, rose et musc.','',false,148,'frais','in_stock'),
('Miss Dior','Christian Dior','FEMMES','Femme',50,'Musc, pivoine et groseille.','',false,149,'frais','in_stock'),
('J''adore','Christian Dior','FEMMES','Femme',50,'Ylang-ylang, rose et magnolia.','',true,150,'frais','in_stock'),
('Hypnotic Poison','Christian Dior','FEMMES','Femme',50,'Amande, vanille et musc enchanteur.','',false,151,'frais','in_stock'),
('Flowerbomb','Viktor & Rolf','FEMMES','Femme',50,'Jasmin, rose et patchouli explosif.','',true,152,'frais','in_stock'),
('Crystal Noir','Versace','FEMMES','Femme',50,'Gardénia, noix de coco et ambre.','',false,153,'frais','in_stock'),
('Bright Crystal','Versace','FEMMES','Femme',50,'Pivoine, magnolia et musc frais.','',false,154,'frais','in_stock'),
('Eros Pour Femme','Versace','FEMMES','Femme',50,'Grenade, citron et pamplemousse.','',false,155,'frais','in_stock'),
('Narciso Rodriguez For Her','Narciso Rodriguez','FEMMES','Femme',50,'Musc sensuel et fleur d''oranger.','',false,156,'frais','in_stock'),
('Candy','Prada','FEMMES','Femme',50,'Caramel, vanille et benjoin doux.','',false,157,'frais','in_stock'),
('Alien','Thierry Mugler','FEMMES','Femme',50,'Jasmin solaire et bois de cachemire.','',true,158,'frais','in_stock'),
('Angel','Thierry Mugler','FEMMES','Femme',50,'Patchouli, miel et vanille mythique.','',false,159,'frais','in_stock'),
('Euphoria','Calvin Klein','FEMMES','Femme',50,'Grenade, kaki et orchidée.','',false,160,'frais','in_stock'),
('Her','Burberry','FEMMES','Femme',50,'Fraise, framboise et jasmin vibrant.','',false,161,'frais','in_stock'),
('Daisy','Marc Jacobs','FEMMES','Femme',50,'Fraise, violette et jasmin champêtre.','',false,162,'frais','in_stock'),
('Be Delicious','DKNY','FEMMES','Femme',50,'Pomme verte, magnolia et musc blanc.','',false,163,'frais','in_stock'),
('Amor Amor','Cacharel','FEMMES','Femme',50,'Pamplemousse, violette et musc rose.','',false,164,'frais','in_stock'),
('Chance Eau Tendre','Chanel','FEMMES','Femme',50,'Grapefruit, jasmin et musc délicat.','',false,165,'frais','in_stock'),
('Chance','Chanel','FEMMES','Femme',50,'Citrus, jasmin et patchouli frais.','',false,166,'frais','in_stock'),
('N°5','Chanel','FEMMES','Femme',50,'Aldéhyde, rose et ylang-ylang mythique.','',false,167,'frais','in_stock'),
('Mon Guerlain','Guerlain','FEMMES','Femme',50,'Lavande, bergamote et vanille gourmande.','',false,168,'frais','in_stock'),
('La Petite Robe Noire','Guerlain','FEMMES','Femme',50,'Thé noir, cerise et rose.','',false,169,'frais','in_stock'),
('Donna Born In Roma','Valentino','FEMMES','Femme',50,'Iris, vanille et bois de santal.','',false,170,'frais','in_stock'),
('Alive','Hugo Boss','FEMMES','Femme',50,'Pomme, jasmin et bois ambré.','',false,171,'frais','in_stock'),
('L''Eau d''Issey','Issey Miyake','FEMMES','Femme',50,'Lotus, musc et bois de rose.','',false,172,'frais','in_stock'),
('212 Sexy','Carolina Herrera','FEMMES','Femme',50,'Mandarine, jasmin et musc sensuel.','',false,173,'frais','in_stock'),
('Pure Poison','Christian Dior','FEMMES','Femme',50,'Jasmin blanc, orange et santal.','',false,174,'frais','in_stock'),
('Addict','Christian Dior','FEMMES','Femme',50,'Vanille et magnolia envoûtants.','',false,175,'frais','in_stock'),
('Gucci Bloom','Gucci','FEMMES','Femme',50,'Jasmin, rose et gardénia naturel.','',false,176,'frais','in_stock'),
('Guilty Pour Femme','Gucci','FEMMES','Femme',50,'Pêche, mandarine et jasmin.','',false,177,'frais','in_stock'),
('Pleasures','Estée Lauder','FEMMES','Femme',50,'Rose, lilas et patchouli printanier.','',false,178,'frais','in_stock'),
('Beautiful','Estée Lauder','FEMMES','Femme',50,'Rose, jasmin et musc élégant.','',false,179,'frais','in_stock'),
('Rose Rush','Lattafa','FEMMES','Femme',50,'Rose, musc et vanille légère.','',false,180,'frais','in_stock'),
('Yara','Lattafa','FEMMES','Femme',50,'Pêche, jasmin et musc rose.','',true,181,'frais','in_stock'),
('Hayati','Rasasi','FEMMES','Femme',50,'Floral doux et musqué oriental.','',false,182,'frais','in_stock'),
('Khizana','Al Haramain','FEMMES','Femme',50,'Rose et musc envoûtants.','',false,183,'frais','in_stock'),
('Mayar','Swiss Arabian','FEMMES','Femme',50,'Floral oriental délicat.','',false,184,'frais','in_stock');

-- ============================================================
-- BLOCK 4: ORIENTAUX (35 parfums)
-- ============================================================
INSERT INTO perfumes (name, brand, category, gender, price, description, image_url, best_seller, sort_order, scent, stock_status)
VALUES
('Oud Maknoon','Lattafa','ORIENTAUX','Mixte',50,'Oud profond, safran et ambre royal.','',true,185,'frais','in_stock'),
('Asad','Lattafa','ORIENTAUX','Homme',50,'Citrus vif, boisé et musc puissant.','',false,186,'frais','in_stock'),
('Badee Al Oud Amethyst','Lattafa','ORIENTAUX','Mixte',50,'Oud violet, fruits exotiques et vanille.','',false,187,'frais','in_stock'),
('Ana Abiyedh Parfum','Lattafa','ORIENTAUX','Femme',50,'Musc blanc pur, oud et rose.','',false,188,'frais','in_stock'),
('Yara Tous','Lattafa','ORIENTAUX','Mixte',50,'Rose, musc et notes fruitées douces.','',false,189,'frais','in_stock'),
('Oud Mood Reminiscence','Lattafa','ORIENTAUX','Mixte',50,'Oud, rose et ambre enveloppants.','',false,190,'frais','in_stock'),
('Ameer Al Oud','Lattafa','ORIENTAUX','Mixte',50,'Oud intense et royal, musc et santal.','',false,191,'frais','in_stock'),
('Raghba Wood Intense','Lattafa','ORIENTAUX','Mixte',50,'Bois d''oud intense et résineux.','',false,192,'frais','in_stock'),
('Qafiya 95','Swiss Arabian','ORIENTAUX','Homme',50,'Oud, encens et musc oriental profond.','',false,193,'frais','in_stock'),
('Shaghaf Oud Aswad','Swiss Arabian','ORIENTAUX','Mixte',50,'Oud noir, rose ambré et épices.','',true,194,'frais','in_stock'),
('Ghawali','Swiss Arabian','ORIENTAUX','Femme',50,'Floral oriental précieux et délicat.','',false,195,'frais','in_stock'),
('Tharwah Gold','Swiss Arabian','ORIENTAUX','Homme',50,'Oud royal, safran et notes boisées.','',false,196,'frais','in_stock'),
('Bait Al Bakhoor','Swiss Arabian','ORIENTAUX','Mixte',50,'Encens traditionnel, oud et santal.','',false,197,'frais','in_stock'),
('Amber Oud Tobacco Edition','Al Haramain','ORIENTAUX','Mixte',50,'Ambre riche, tabac blond et oud.','',true,198,'frais','in_stock'),
('Amber Oud Gold Edition','Al Haramain','ORIENTAUX','Mixte',50,'Ambre somptueux et oud précieux.','',false,199,'frais','in_stock'),
('All The Money','Al Haramain','ORIENTAUX','Homme',50,'Citrus vif, boisé et musc luxueux.','',false,200,'frais','in_stock'),
('Musk Tahara','Al Haramain','ORIENTAUX','Femme',50,'Musc blanc pur et poudré.','',false,201,'frais','in_stock'),
('Oud Cambodi','Al Haramain','ORIENTAUX','Mixte',50,'Oud du Cambodge pur et résineux.','',false,202,'frais','in_stock'),
('La Yuqawam Pour Homme','Rasasi','ORIENTAUX','Homme',50,'Oud intense, rose et ambre oriental.','',false,203,'frais','in_stock'),
('Dakhon','Rasasi','ORIENTAUX','Mixte',50,'Fumé, oud profond et ambré.','',false,204,'frais','in_stock'),
('Faris','Rasasi','ORIENTAUX','Homme',50,'Boisé épicé arabe et cuir.','',false,205,'frais','in_stock'),
('Egra','Rasasi','ORIENTAUX','Mixte',50,'Floral oriental délicat et musqué.','',false,206,'frais','in_stock'),
('Mukhallat Malaki','Rasasi','ORIENTAUX','Mixte',50,'Mélange royal arabe, oud et épices.','',false,207,'frais','in_stock'),
('Daw Al Oud','Ajmal','ORIENTAUX','Mixte',50,'Lumière d''oud, jasmin et ambre.','',false,208,'frais','in_stock'),
('Evoke Gold','Ajmal','ORIENTAUX','Homme',50,'Oud, cuir et ambre sophistiqués.','',false,209,'frais','in_stock'),
('Barakkat Rouge 540','Fragrance World','ORIENTAUX','Mixte',50,'Safran, ambre et oud somptueux.','',true,210,'frais','in_stock'),
('Club de Nuit Intense Man','Armaf','ORIENTAUX','Homme',50,'Oud, bergamote et cuir intense.','',true,211,'frais','in_stock'),
('Club de Nuit Intense Woman','Armaf','ORIENTAUX','Femme',50,'Floral fruité et boisé élégant.','',false,212,'frais','in_stock'),
('Golden Oud','Armaf','ORIENTAUX','Mixte',50,'Oud doré, santal et épices chaudes.','',false,213,'frais','in_stock'),
('Oud For Glory','Maison Oud','ORIENTAUX','Mixte',50,'Oud noble, rose et ambre précieux.','',false,214,'frais','in_stock'),
('Rose Oud','Nusuk','ORIENTAUX','Mixte',50,'Rose épanouie et oud harmonieux.','',false,215,'frais','in_stock'),
('Oud Safi','Nusuk','ORIENTAUX','Mixte',50,'Oud pur, bois de santal et musc.','',false,216,'frais','in_stock'),
('Oud Al Layl','Arabian Oud','ORIENTAUX','Mixte',50,'Oud nocturne, encens et ambre.','',false,217,'frais','in_stock'),
('Kalemat','Arabian Oud','ORIENTAUX','Mixte',50,'Ambre noir, oud fumé et musc.','',true,218,'frais','in_stock'),
('Rouat Al Oud','Arabian Oud','ORIENTAUX','Homme',50,'Oud majestueux et boisé oriental.','',false,219,'frais','in_stock');
