/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ParfumeurRouteImport } from './routes/parfumeur'
import { Route as AdminpannelRouteImport } from './routes/adminpannel'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminpannelIndexRouteImport } from './routes/adminpannel.index'
import { Route as ParfumIdRouteImport } from './routes/parfum.$id'
import { Route as AdminpannelPerfumesRouteImport } from './routes/adminpannel.perfumes'
import { Route as AdminpannelOrdersRouteImport } from './routes/adminpannel.orders'

const ParfumeurRoute = ParfumeurRouteImport.update({
  id: '/parfumeur',
  path: '/parfumeur',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminpannelRoute = AdminpannelRouteImport.update({
  id: '/adminpannel',
  path: '/adminpannel',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminpannelIndexRoute = AdminpannelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminpannelRoute,
} as any)
const ParfumIdRoute = ParfumIdRouteImport.update({
  id: '/parfum/$id',
  path: '/parfum/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminpannelPerfumesRoute = AdminpannelPerfumesRouteImport.update({
  id: '/perfumes',
  path: '/perfumes',
  getParentRoute: () => AdminpannelRoute,
} as any)
const AdminpannelOrdersRoute = AdminpannelOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminpannelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/adminpannel': typeof AdminpannelRouteWithChildren
  '/parfumeur': typeof ParfumeurRoute
  '/adminpannel/orders': typeof AdminpannelOrdersRoute
  '/adminpannel/perfumes': typeof AdminpannelPerfumesRoute
  '/parfum/$id': typeof ParfumIdRoute
  '/adminpannel/': typeof AdminpannelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/parfumeur': typeof ParfumeurRoute
  '/adminpannel/orders': typeof AdminpannelOrdersRoute
  '/adminpannel/perfumes': typeof AdminpannelPerfumesRoute
  '/parfum/$id': typeof ParfumIdRoute
  '/adminpannel': typeof AdminpannelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/adminpannel': typeof AdminpannelRouteWithChildren
  '/parfumeur': typeof ParfumeurRoute
  '/adminpannel/orders': typeof AdminpannelOrdersRoute
  '/adminpannel/perfumes': typeof AdminpannelPerfumesRoute
  '/parfum/$id': typeof ParfumIdRoute
  '/adminpannel/': typeof AdminpannelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/adminpannel'
    | '/parfumeur'
    | '/adminpannel/orders'
    | '/adminpannel/perfumes'
    | '/parfum/$id'
    | '/adminpannel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/parfumeur'
    | '/adminpannel/orders'
    | '/adminpannel/perfumes'
    | '/parfum/$id'
    | '/adminpannel'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/adminpannel'
    | '/parfumeur'
    | '/adminpannel/orders'
    | '/adminpannel/perfumes'
    | '/parfum/$id'
    | '/adminpannel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminpannelRoute: typeof AdminpannelRouteWithChildren
  ParfumeurRoute: typeof ParfumeurRoute
  ParfumIdRoute: typeof ParfumIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/parfumeur': {
      id: '/parfumeur'
      path: '/parfumeur'
      fullPath: '/parfumeur'
      preLoaderRoute: typeof ParfumeurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminpannel': {
      id: '/adminpannel'
      path: '/adminpannel'
      fullPath: '/adminpannel'
      preLoaderRoute: typeof AdminpannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminpannel/': {
      id: '/adminpannel/'
      path: '/'
      fullPath: '/adminpannel/'
      preLoaderRoute: typeof AdminpannelIndexRouteImport
      parentRoute: typeof AdminpannelRoute
    }
    '/parfum/$id': {
      id: '/parfum/$id'
      path: '/parfum/$id'
      fullPath: '/parfum/$id'
      preLoaderRoute: typeof ParfumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminpannel/perfumes': {
      id: '/adminpannel/perfumes'
      path: '/perfumes'
      fullPath: '/adminpannel/perfumes'
      preLoaderRoute: typeof AdminpannelPerfumesRouteImport
      parentRoute: typeof AdminpannelRoute
    }
    '/adminpannel/orders': {
      id: '/adminpannel/orders'
      path: '/orders'
      fullPath: '/adminpannel/orders'
      preLoaderRoute: typeof AdminpannelOrdersRouteImport
      parentRoute: typeof AdminpannelRoute
    }
  }
}

interface AdminpannelRouteChildren {
  AdminpannelOrdersRoute: typeof AdminpannelOrdersRoute
  AdminpannelPerfumesRoute: typeof AdminpannelPerfumesRoute
  AdminpannelIndexRoute: typeof AdminpannelIndexRoute
}

const AdminpannelRouteChildren: AdminpannelRouteChildren = {
  AdminpannelOrdersRoute: AdminpannelOrdersRoute,
  AdminpannelPerfumesRoute: AdminpannelPerfumesRoute,
  AdminpannelIndexRoute: AdminpannelIndexRoute,
}

const AdminpannelRouteWithChildren = AdminpannelRoute._addFileChildren(
  AdminpannelRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminpannelRoute: AdminpannelRouteWithChildren,
  ParfumeurRoute: ParfumeurRoute,
  ParfumIdRoute: ParfumIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
